# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_91b0_rx_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_91b0_rx_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_91b0_rx_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_91b0_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_91b0_rx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_91b0_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_91b0_rx_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_91b0_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_91b0_rx_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_91b0_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_mipi_csi2_rx_subsyst_0_0/bd_0/ip/ip_1/bd_91b0_rx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_91b0_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
