// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_rect_entry304 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        xleft_s_dout,
        xleft_s_empty_n,
        xleft_s_read,
        xright_s_dout,
        xright_s_empty_n,
        xright_s_read,
        ytop_s_dout,
        ytop_s_empty_n,
        ytop_s_read,
        ydown_s_dout,
        ydown_s_empty_n,
        ydown_s_read,
        color1_dout,
        color1_empty_n,
        color1_read,
        color2_dout,
        color2_empty_n,
        color2_read,
        color3_dout,
        color3_empty_n,
        color3_read,
        char1_dout,
        char1_empty_n,
        char1_read,
        char2_dout,
        char2_empty_n,
        char2_read,
        char3_dout,
        char3_empty_n,
        char3_read,
        char4_dout,
        char4_empty_n,
        char4_read,
        char5_dout,
        char5_empty_n,
        char5_read,
        char6_dout,
        char6_empty_n,
        char6_read,
        xleft_out_din,
        xleft_out_full_n,
        xleft_out_write,
        xleft_out1_din,
        xleft_out1_full_n,
        xleft_out1_write,
        xright_out_din,
        xright_out_full_n,
        xright_out_write,
        ytop_out_din,
        ytop_out_full_n,
        ytop_out_write,
        ydown_out_din,
        ydown_out_full_n,
        ydown_out_write,
        color1_out_din,
        color1_out_full_n,
        color1_out_write,
        color2_out_din,
        color2_out_full_n,
        color2_out_write,
        color3_out_din,
        color3_out_full_n,
        color3_out_write,
        char1_out_din,
        char1_out_full_n,
        char1_out_write,
        char2_out_din,
        char2_out_full_n,
        char2_out_write,
        char3_out_din,
        char3_out_full_n,
        char3_out_write,
        char4_out_din,
        char4_out_full_n,
        char4_out_write,
        char5_out_din,
        char5_out_full_n,
        char5_out_write,
        char6_out_din,
        char6_out_full_n,
        char6_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] xleft_s_dout;
input   xleft_s_empty_n;
output   xleft_s_read;
input  [15:0] xright_s_dout;
input   xright_s_empty_n;
output   xright_s_read;
input  [15:0] ytop_s_dout;
input   ytop_s_empty_n;
output   ytop_s_read;
input  [15:0] ydown_s_dout;
input   ydown_s_empty_n;
output   ydown_s_read;
input  [7:0] color1_dout;
input   color1_empty_n;
output   color1_read;
input  [7:0] color2_dout;
input   color2_empty_n;
output   color2_read;
input  [7:0] color3_dout;
input   color3_empty_n;
output   color3_read;
input  [7:0] char1_dout;
input   char1_empty_n;
output   char1_read;
input  [7:0] char2_dout;
input   char2_empty_n;
output   char2_read;
input  [7:0] char3_dout;
input   char3_empty_n;
output   char3_read;
input  [7:0] char4_dout;
input   char4_empty_n;
output   char4_read;
input  [7:0] char5_dout;
input   char5_empty_n;
output   char5_read;
input  [7:0] char6_dout;
input   char6_empty_n;
output   char6_read;
output  [15:0] xleft_out_din;
input   xleft_out_full_n;
output   xleft_out_write;
output  [15:0] xleft_out1_din;
input   xleft_out1_full_n;
output   xleft_out1_write;
output  [15:0] xright_out_din;
input   xright_out_full_n;
output   xright_out_write;
output  [15:0] ytop_out_din;
input   ytop_out_full_n;
output   ytop_out_write;
output  [15:0] ydown_out_din;
input   ydown_out_full_n;
output   ydown_out_write;
output  [7:0] color1_out_din;
input   color1_out_full_n;
output   color1_out_write;
output  [7:0] color2_out_din;
input   color2_out_full_n;
output   color2_out_write;
output  [7:0] color3_out_din;
input   color3_out_full_n;
output   color3_out_write;
output  [7:0] char1_out_din;
input   char1_out_full_n;
output   char1_out_write;
output  [7:0] char2_out_din;
input   char2_out_full_n;
output   char2_out_write;
output  [7:0] char3_out_din;
input   char3_out_full_n;
output   char3_out_write;
output  [7:0] char4_out_din;
input   char4_out_full_n;
output   char4_out_write;
output  [7:0] char5_out_din;
input   char5_out_full_n;
output   char5_out_write;
output  [7:0] char6_out_din;
input   char6_out_full_n;
output   char6_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg xleft_s_read;
reg xright_s_read;
reg ytop_s_read;
reg ydown_s_read;
reg color1_read;
reg color2_read;
reg color3_read;
reg char1_read;
reg char2_read;
reg char3_read;
reg char4_read;
reg char5_read;
reg char6_read;
reg xleft_out_write;
reg xleft_out1_write;
reg xright_out_write;
reg ytop_out_write;
reg ydown_out_write;
reg color1_out_write;
reg color2_out_write;
reg color3_out_write;
reg char1_out_write;
reg char2_out_write;
reg char3_out_write;
reg char4_out_write;
reg char5_out_write;
reg char6_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    xleft_s_blk_n;
reg    xright_s_blk_n;
reg    ytop_s_blk_n;
reg    ydown_s_blk_n;
reg    color1_blk_n;
reg    color2_blk_n;
reg    color3_blk_n;
reg    char1_blk_n;
reg    char2_blk_n;
reg    char3_blk_n;
reg    char4_blk_n;
reg    char5_blk_n;
reg    char6_blk_n;
reg    xleft_out_blk_n;
reg    xleft_out1_blk_n;
reg    xright_out_blk_n;
reg    ytop_out_blk_n;
reg    ydown_out_blk_n;
reg    color1_out_blk_n;
reg    color2_out_blk_n;
reg    color3_out_blk_n;
reg    char1_out_blk_n;
reg    char2_out_blk_n;
reg    char3_out_blk_n;
reg    char4_out_blk_n;
reg    char5_out_blk_n;
reg    char6_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char1_blk_n = char1_empty_n;
    end else begin
        char1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char1_out_blk_n = char1_out_full_n;
    end else begin
        char1_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char1_out_write = 1'b1;
    end else begin
        char1_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char1_read = 1'b1;
    end else begin
        char1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char2_blk_n = char2_empty_n;
    end else begin
        char2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char2_out_blk_n = char2_out_full_n;
    end else begin
        char2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char2_out_write = 1'b1;
    end else begin
        char2_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char2_read = 1'b1;
    end else begin
        char2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char3_blk_n = char3_empty_n;
    end else begin
        char3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char3_out_blk_n = char3_out_full_n;
    end else begin
        char3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char3_out_write = 1'b1;
    end else begin
        char3_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char3_read = 1'b1;
    end else begin
        char3_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char4_blk_n = char4_empty_n;
    end else begin
        char4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char4_out_blk_n = char4_out_full_n;
    end else begin
        char4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char4_out_write = 1'b1;
    end else begin
        char4_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char4_read = 1'b1;
    end else begin
        char4_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char5_blk_n = char5_empty_n;
    end else begin
        char5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char5_out_blk_n = char5_out_full_n;
    end else begin
        char5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char5_out_write = 1'b1;
    end else begin
        char5_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char5_read = 1'b1;
    end else begin
        char5_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char6_blk_n = char6_empty_n;
    end else begin
        char6_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char6_out_blk_n = char6_out_full_n;
    end else begin
        char6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char6_out_write = 1'b1;
    end else begin
        char6_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        char6_read = 1'b1;
    end else begin
        char6_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color1_blk_n = color1_empty_n;
    end else begin
        color1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color1_out_blk_n = color1_out_full_n;
    end else begin
        color1_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color1_out_write = 1'b1;
    end else begin
        color1_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color1_read = 1'b1;
    end else begin
        color1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color2_blk_n = color2_empty_n;
    end else begin
        color2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color2_out_blk_n = color2_out_full_n;
    end else begin
        color2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color2_out_write = 1'b1;
    end else begin
        color2_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color2_read = 1'b1;
    end else begin
        color2_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color3_blk_n = color3_empty_n;
    end else begin
        color3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color3_out_blk_n = color3_out_full_n;
    end else begin
        color3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color3_out_write = 1'b1;
    end else begin
        color3_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        color3_read = 1'b1;
    end else begin
        color3_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_out1_blk_n = xleft_out1_full_n;
    end else begin
        xleft_out1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_out1_write = 1'b1;
    end else begin
        xleft_out1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_out_blk_n = xleft_out_full_n;
    end else begin
        xleft_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_out_write = 1'b1;
    end else begin
        xleft_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_s_blk_n = xleft_s_empty_n;
    end else begin
        xleft_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xleft_s_read = 1'b1;
    end else begin
        xleft_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xright_out_blk_n = xright_out_full_n;
    end else begin
        xright_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xright_out_write = 1'b1;
    end else begin
        xright_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xright_s_blk_n = xright_s_empty_n;
    end else begin
        xright_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        xright_s_read = 1'b1;
    end else begin
        xright_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ydown_out_blk_n = ydown_out_full_n;
    end else begin
        ydown_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ydown_out_write = 1'b1;
    end else begin
        ydown_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ydown_s_blk_n = ydown_s_empty_n;
    end else begin
        ydown_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ydown_s_read = 1'b1;
    end else begin
        ydown_s_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ytop_out_blk_n = ytop_out_full_n;
    end else begin
        ytop_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ytop_out_write = 1'b1;
    end else begin
        ytop_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ytop_s_blk_n = ytop_s_empty_n;
    end else begin
        ytop_s_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ytop_s_read = 1'b1;
    end else begin
        ytop_s_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((xright_out_full_n == 1'b0) | (xleft_out1_full_n == 1'b0) | (xleft_out_full_n == 1'b0) | (char6_empty_n == 1'b0) | (char5_empty_n == 1'b0) | (char4_empty_n == 1'b0) | (char3_empty_n == 1'b0) | (char2_empty_n == 1'b0) | (real_start == 1'b0) | (char1_empty_n == 1'b0) | (color3_empty_n == 1'b0) | (color2_empty_n == 1'b0) | (color1_empty_n == 1'b0) | (ydown_s_empty_n == 1'b0) | (ytop_s_empty_n == 1'b0) | (xright_s_empty_n == 1'b0) | (xleft_s_empty_n == 1'b0) | (char6_out_full_n == 1'b0) | (char5_out_full_n == 1'b0) | (char4_out_full_n == 1'b0) | (char3_out_full_n == 1'b0) | (char2_out_full_n == 1'b0) | (char1_out_full_n == 1'b0) | (color3_out_full_n == 1'b0) | (color2_out_full_n == 1'b0) | (color1_out_full_n == 1'b0) | (ydown_out_full_n == 1'b0) | (ytop_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign char1_out_din = char1_dout;

assign char2_out_din = char2_dout;

assign char3_out_din = char3_dout;

assign char4_out_din = char4_dout;

assign char5_out_din = char5_dout;

assign char6_out_din = char6_dout;

assign color1_out_din = color1_dout;

assign color2_out_din = color2_dout;

assign color3_out_din = color3_dout;

assign start_out = real_start;

assign xleft_out1_din = xleft_s_dout;

assign xleft_out_din = xleft_s_dout;

assign xright_out_din = xright_s_dout;

assign ydown_out_din = ydown_s_dout;

assign ytop_out_din = ytop_s_dout;

endmodule //hls_rect_entry304
