-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_rect_entry304 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    xleft_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    xleft_s_empty_n : IN STD_LOGIC;
    xleft_s_read : OUT STD_LOGIC;
    xright_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    xright_s_empty_n : IN STD_LOGIC;
    xright_s_read : OUT STD_LOGIC;
    ytop_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ytop_s_empty_n : IN STD_LOGIC;
    ytop_s_read : OUT STD_LOGIC;
    ydown_s_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    ydown_s_empty_n : IN STD_LOGIC;
    ydown_s_read : OUT STD_LOGIC;
    color1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    color1_empty_n : IN STD_LOGIC;
    color1_read : OUT STD_LOGIC;
    color2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    color2_empty_n : IN STD_LOGIC;
    color2_read : OUT STD_LOGIC;
    color3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    color3_empty_n : IN STD_LOGIC;
    color3_read : OUT STD_LOGIC;
    char1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char1_empty_n : IN STD_LOGIC;
    char1_read : OUT STD_LOGIC;
    char2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char2_empty_n : IN STD_LOGIC;
    char2_read : OUT STD_LOGIC;
    char3_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char3_empty_n : IN STD_LOGIC;
    char3_read : OUT STD_LOGIC;
    char4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char4_empty_n : IN STD_LOGIC;
    char4_read : OUT STD_LOGIC;
    char5_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char5_empty_n : IN STD_LOGIC;
    char5_read : OUT STD_LOGIC;
    char6_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    char6_empty_n : IN STD_LOGIC;
    char6_read : OUT STD_LOGIC;
    xleft_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    xleft_out_full_n : IN STD_LOGIC;
    xleft_out_write : OUT STD_LOGIC;
    xleft_out1_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    xleft_out1_full_n : IN STD_LOGIC;
    xleft_out1_write : OUT STD_LOGIC;
    xright_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    xright_out_full_n : IN STD_LOGIC;
    xright_out_write : OUT STD_LOGIC;
    ytop_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    ytop_out_full_n : IN STD_LOGIC;
    ytop_out_write : OUT STD_LOGIC;
    ydown_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    ydown_out_full_n : IN STD_LOGIC;
    ydown_out_write : OUT STD_LOGIC;
    color1_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    color1_out_full_n : IN STD_LOGIC;
    color1_out_write : OUT STD_LOGIC;
    color2_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    color2_out_full_n : IN STD_LOGIC;
    color2_out_write : OUT STD_LOGIC;
    color3_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    color3_out_full_n : IN STD_LOGIC;
    color3_out_write : OUT STD_LOGIC;
    char1_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    char1_out_full_n : IN STD_LOGIC;
    char1_out_write : OUT STD_LOGIC;
    char2_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    char2_out_full_n : IN STD_LOGIC;
    char2_out_write : OUT STD_LOGIC;
    char3_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    char3_out_full_n : IN STD_LOGIC;
    char3_out_write : OUT STD_LOGIC;
    char4_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    char4_out_full_n : IN STD_LOGIC;
    char4_out_write : OUT STD_LOGIC;
    char5_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    char5_out_full_n : IN STD_LOGIC;
    char5_out_write : OUT STD_LOGIC;
    char6_out_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    char6_out_full_n : IN STD_LOGIC;
    char6_out_write : OUT STD_LOGIC );
end;


architecture behav of hls_rect_entry304 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal xleft_s_blk_n : STD_LOGIC;
    signal xright_s_blk_n : STD_LOGIC;
    signal ytop_s_blk_n : STD_LOGIC;
    signal ydown_s_blk_n : STD_LOGIC;
    signal color1_blk_n : STD_LOGIC;
    signal color2_blk_n : STD_LOGIC;
    signal color3_blk_n : STD_LOGIC;
    signal char1_blk_n : STD_LOGIC;
    signal char2_blk_n : STD_LOGIC;
    signal char3_blk_n : STD_LOGIC;
    signal char4_blk_n : STD_LOGIC;
    signal char5_blk_n : STD_LOGIC;
    signal char6_blk_n : STD_LOGIC;
    signal xleft_out_blk_n : STD_LOGIC;
    signal xleft_out1_blk_n : STD_LOGIC;
    signal xright_out_blk_n : STD_LOGIC;
    signal ytop_out_blk_n : STD_LOGIC;
    signal ydown_out_blk_n : STD_LOGIC;
    signal color1_out_blk_n : STD_LOGIC;
    signal color2_out_blk_n : STD_LOGIC;
    signal color3_out_blk_n : STD_LOGIC;
    signal char1_out_blk_n : STD_LOGIC;
    signal char2_out_blk_n : STD_LOGIC;
    signal char3_out_blk_n : STD_LOGIC;
    signal char4_out_blk_n : STD_LOGIC;
    signal char5_out_blk_n : STD_LOGIC;
    signal char6_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
                ap_block_state1 <= ((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    char1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char1_blk_n <= char1_empty_n;
        else 
            char1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char1_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char1_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char1_out_blk_n <= char1_out_full_n;
        else 
            char1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    char1_out_din <= char1_dout;

    char1_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char1_out_write <= ap_const_logic_1;
        else 
            char1_out_write <= ap_const_logic_0;
        end if; 
    end process;


    char1_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char1_read <= ap_const_logic_1;
        else 
            char1_read <= ap_const_logic_0;
        end if; 
    end process;


    char2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char2_blk_n <= char2_empty_n;
        else 
            char2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char2_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char2_out_blk_n <= char2_out_full_n;
        else 
            char2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    char2_out_din <= char2_dout;

    char2_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char2_out_write <= ap_const_logic_1;
        else 
            char2_out_write <= ap_const_logic_0;
        end if; 
    end process;


    char2_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char2_read <= ap_const_logic_1;
        else 
            char2_read <= ap_const_logic_0;
        end if; 
    end process;


    char3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char3_blk_n <= char3_empty_n;
        else 
            char3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char3_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char3_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char3_out_blk_n <= char3_out_full_n;
        else 
            char3_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    char3_out_din <= char3_dout;

    char3_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char3_out_write <= ap_const_logic_1;
        else 
            char3_out_write <= ap_const_logic_0;
        end if; 
    end process;


    char3_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char3_read <= ap_const_logic_1;
        else 
            char3_read <= ap_const_logic_0;
        end if; 
    end process;


    char4_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char4_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char4_blk_n <= char4_empty_n;
        else 
            char4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char4_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char4_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char4_out_blk_n <= char4_out_full_n;
        else 
            char4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    char4_out_din <= char4_dout;

    char4_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char4_out_write <= ap_const_logic_1;
        else 
            char4_out_write <= ap_const_logic_0;
        end if; 
    end process;


    char4_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char4_read <= ap_const_logic_1;
        else 
            char4_read <= ap_const_logic_0;
        end if; 
    end process;


    char5_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char5_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char5_blk_n <= char5_empty_n;
        else 
            char5_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char5_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char5_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char5_out_blk_n <= char5_out_full_n;
        else 
            char5_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    char5_out_din <= char5_dout;

    char5_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char5_out_write <= ap_const_logic_1;
        else 
            char5_out_write <= ap_const_logic_0;
        end if; 
    end process;


    char5_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char5_read <= ap_const_logic_1;
        else 
            char5_read <= ap_const_logic_0;
        end if; 
    end process;


    char6_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char6_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char6_blk_n <= char6_empty_n;
        else 
            char6_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    char6_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, char6_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char6_out_blk_n <= char6_out_full_n;
        else 
            char6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    char6_out_din <= char6_dout;

    char6_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char6_out_write <= ap_const_logic_1;
        else 
            char6_out_write <= ap_const_logic_0;
        end if; 
    end process;


    char6_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            char6_read <= ap_const_logic_1;
        else 
            char6_read <= ap_const_logic_0;
        end if; 
    end process;


    color1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color1_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color1_blk_n <= color1_empty_n;
        else 
            color1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    color1_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color1_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color1_out_blk_n <= color1_out_full_n;
        else 
            color1_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    color1_out_din <= color1_dout;

    color1_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color1_out_write <= ap_const_logic_1;
        else 
            color1_out_write <= ap_const_logic_0;
        end if; 
    end process;


    color1_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color1_read <= ap_const_logic_1;
        else 
            color1_read <= ap_const_logic_0;
        end if; 
    end process;


    color2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color2_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color2_blk_n <= color2_empty_n;
        else 
            color2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    color2_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color2_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color2_out_blk_n <= color2_out_full_n;
        else 
            color2_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    color2_out_din <= color2_dout;

    color2_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color2_out_write <= ap_const_logic_1;
        else 
            color2_out_write <= ap_const_logic_0;
        end if; 
    end process;


    color2_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color2_read <= ap_const_logic_1;
        else 
            color2_read <= ap_const_logic_0;
        end if; 
    end process;


    color3_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color3_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color3_blk_n <= color3_empty_n;
        else 
            color3_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    color3_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, color3_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color3_out_blk_n <= color3_out_full_n;
        else 
            color3_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    color3_out_din <= color3_dout;

    color3_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color3_out_write <= ap_const_logic_1;
        else 
            color3_out_write <= ap_const_logic_0;
        end if; 
    end process;


    color3_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            color3_read <= ap_const_logic_1;
        else 
            color3_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    xleft_out1_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_out1_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xleft_out1_blk_n <= xleft_out1_full_n;
        else 
            xleft_out1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xleft_out1_din <= xleft_s_dout;

    xleft_out1_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xleft_out1_write <= ap_const_logic_1;
        else 
            xleft_out1_write <= ap_const_logic_0;
        end if; 
    end process;


    xleft_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xleft_out_blk_n <= xleft_out_full_n;
        else 
            xleft_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xleft_out_din <= xleft_s_dout;

    xleft_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xleft_out_write <= ap_const_logic_1;
        else 
            xleft_out_write <= ap_const_logic_0;
        end if; 
    end process;


    xleft_s_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xleft_s_blk_n <= xleft_s_empty_n;
        else 
            xleft_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    xleft_s_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xleft_s_read <= ap_const_logic_1;
        else 
            xleft_s_read <= ap_const_logic_0;
        end if; 
    end process;


    xright_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xright_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xright_out_blk_n <= xright_out_full_n;
        else 
            xright_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    xright_out_din <= xright_s_dout;

    xright_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xright_out_write <= ap_const_logic_1;
        else 
            xright_out_write <= ap_const_logic_0;
        end if; 
    end process;


    xright_s_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xright_s_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xright_s_blk_n <= xright_s_empty_n;
        else 
            xright_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    xright_s_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            xright_s_read <= ap_const_logic_1;
        else 
            xright_s_read <= ap_const_logic_0;
        end if; 
    end process;


    ydown_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ydown_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ydown_out_blk_n <= ydown_out_full_n;
        else 
            ydown_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ydown_out_din <= ydown_s_dout;

    ydown_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ydown_out_write <= ap_const_logic_1;
        else 
            ydown_out_write <= ap_const_logic_0;
        end if; 
    end process;


    ydown_s_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ydown_s_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ydown_s_blk_n <= ydown_s_empty_n;
        else 
            ydown_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ydown_s_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ydown_s_read <= ap_const_logic_1;
        else 
            ydown_s_read <= ap_const_logic_0;
        end if; 
    end process;


    ytop_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ytop_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ytop_out_blk_n <= ytop_out_full_n;
        else 
            ytop_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ytop_out_din <= ytop_s_dout;

    ytop_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ytop_out_write <= ap_const_logic_1;
        else 
            ytop_out_write <= ap_const_logic_0;
        end if; 
    end process;


    ytop_s_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, ytop_s_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ytop_s_blk_n <= ytop_s_empty_n;
        else 
            ytop_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ytop_s_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, xleft_s_empty_n, xright_s_empty_n, ytop_s_empty_n, ydown_s_empty_n, color1_empty_n, color2_empty_n, color3_empty_n, char1_empty_n, char2_empty_n, char3_empty_n, char4_empty_n, char5_empty_n, char6_empty_n, xleft_out_full_n, xleft_out1_full_n, xright_out_full_n, ytop_out_full_n, ydown_out_full_n, color1_out_full_n, color2_out_full_n, color3_out_full_n, char1_out_full_n, char2_out_full_n, char3_out_full_n, char4_out_full_n, char5_out_full_n, char6_out_full_n)
    begin
        if ((not(((xright_out_full_n = ap_const_logic_0) or (xleft_out1_full_n = ap_const_logic_0) or (xleft_out_full_n = ap_const_logic_0) or (char6_empty_n = ap_const_logic_0) or (char5_empty_n = ap_const_logic_0) or (char4_empty_n = ap_const_logic_0) or (char3_empty_n = ap_const_logic_0) or (char2_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (char1_empty_n = ap_const_logic_0) or (color3_empty_n = ap_const_logic_0) or (color2_empty_n = ap_const_logic_0) or (color1_empty_n = ap_const_logic_0) or (ydown_s_empty_n = ap_const_logic_0) or (ytop_s_empty_n = ap_const_logic_0) or (xright_s_empty_n = ap_const_logic_0) or (xleft_s_empty_n = ap_const_logic_0) or (char6_out_full_n = ap_const_logic_0) or (char5_out_full_n = ap_const_logic_0) or (char4_out_full_n = ap_const_logic_0) or (char3_out_full_n = ap_const_logic_0) or (char2_out_full_n = ap_const_logic_0) or (char1_out_full_n = ap_const_logic_0) or (color3_out_full_n = ap_const_logic_0) or (color2_out_full_n = ap_const_logic_0) or (color1_out_full_n = ap_const_logic_0) or (ydown_out_full_n = ap_const_logic_0) or (ytop_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ytop_s_read <= ap_const_logic_1;
        else 
            ytop_s_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
