# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0.xci
# IP: The module: 'cam_rst_ps8_0_250M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_rst_ps8_0_250M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_rst_ps8_0_250M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_rst_ps8_0_250M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0.xci
# IP: The module: 'cam_rst_ps8_0_250M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_rst_ps8_0_250M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_rst_ps8_0_250M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_rst_ps8_0_250M_0/cam_rst_ps8_0_250M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_rst_ps8_0_250M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
