// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Block_proc_HH_
#define _Block_proc_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct Block_proc : public sc_module {
    // Port declarations 25
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > xleft_s_dout;
    sc_in< sc_logic > xleft_s_empty_n;
    sc_out< sc_logic > xleft_s_read;
    sc_out< sc_lv<16> > ch2x_out_out_din;
    sc_in< sc_logic > ch2x_out_out_full_n;
    sc_out< sc_logic > ch2x_out_out_write;
    sc_out< sc_lv<16> > ch3x_out_out_din;
    sc_in< sc_logic > ch3x_out_out_full_n;
    sc_out< sc_logic > ch3x_out_out_write;
    sc_out< sc_lv<16> > ch4x_out_out_din;
    sc_in< sc_logic > ch4x_out_out_full_n;
    sc_out< sc_logic > ch4x_out_out_write;
    sc_out< sc_lv<16> > ch5x_out_out_din;
    sc_in< sc_logic > ch5x_out_out_full_n;
    sc_out< sc_logic > ch5x_out_out_write;
    sc_out< sc_lv<16> > ch6x_out_out_din;
    sc_in< sc_logic > ch6x_out_out_full_n;
    sc_out< sc_logic > ch6x_out_out_write;


    // Module declarations
    Block_proc(sc_module_name name);
    SC_HAS_PROCESS(Block_proc);

    ~Block_proc();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > xleft_s_blk_n;
    sc_signal< sc_logic > ch2x_out_out_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ch3x_out_out_blk_n;
    sc_signal< sc_logic > ch4x_out_out_blk_n;
    sc_signal< sc_logic > ch5x_out_out_blk_n;
    sc_signal< sc_logic > ch6x_out_out_blk_n;
    sc_signal< sc_lv<16> > xleft_read_reg_179;
    sc_signal< bool > ap_block_state1;
    sc_signal< bool > ap_block_state2;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<16> ap_const_lv16_20;
    static const sc_lv<16> ap_const_lv16_40;
    static const sc_lv<16> ap_const_lv16_60;
    static const sc_lv<16> ap_const_lv16_80;
    static const sc_lv<16> ap_const_lv16_A0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_block_state1();
    void thread_ap_block_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ch2x_out_out_blk_n();
    void thread_ch2x_out_out_din();
    void thread_ch2x_out_out_write();
    void thread_ch3x_out_out_blk_n();
    void thread_ch3x_out_out_din();
    void thread_ch3x_out_out_write();
    void thread_ch4x_out_out_blk_n();
    void thread_ch4x_out_out_din();
    void thread_ch4x_out_out_write();
    void thread_ch5x_out_out_blk_n();
    void thread_ch5x_out_out_din();
    void thread_ch5x_out_out_write();
    void thread_ch6x_out_out_blk_n();
    void thread_ch6x_out_out_din();
    void thread_ch6x_out_out_write();
    void thread_xleft_s_blk_n();
    void thread_xleft_s_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
