
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhls_preprocess.h"

/*
* The configuration table for devices
*/

XHls_preprocess_Config XHls_preprocess_ConfigTable[XPAR_XHLS_PREPROCESS_NUM_INSTANCES] =
{
	{
		XPAR_HLS_PREPROCESS_0_DEVICE_ID,
		XPAR_HLS_PREPROCESS_0_S_AXI_AXILITES_BASEADDR
	}
};


