# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/base/base.srcs/sources_1/bd/cam/ip/cam_zynq_ultra_ps_e_0_0/cam_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'cam_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_zynq_ultra_ps_e_0_0/cam_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_zynq_ultra_ps_e_0_0/cam_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/base/base.srcs/sources_1/bd/cam/ip/cam_zynq_ultra_ps_e_0_0/cam_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'cam_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_zynq_ultra_ps_e_0_0/cam_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/base/base.srcs/sources_1/bd/cam/ip/cam_zynq_ultra_ps_e_0_0/cam_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cam_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
